<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>item62</name>
   <tag></tag>
   <elementGuidId>39b7f00b-4fc1-4e5b-8d8f-b8aad4ca8c54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[5]/div[2]/div[52]/div/div/div/div/div/div[2]/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fc0e3fe8-98be-4785-8c28-d64dabfcfc6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prd_link-product-name css-3um8ox</value>
      <webElementGuid>a8003246-dd5f-4209-8bcd-ab021c5e8d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>spnSRPProdName</value>
      <webElementGuid>e69b7fb4-cfb8-455a-a322-f6e347178c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apple iPhone 14 5G 512GB 256GB 128GB 512 256 128 GB Garansi 1 Tahun</value>
      <webElementGuid>b573e8cb-fee7-4328-b134-80ed81518c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[@class=&quot;css-jau1bt&quot;]/div[@class=&quot;css-1c82svt&quot;]/div[@class=&quot;css-rjanld&quot;]/div[5]/div[@class=&quot;css-jza1fo&quot;]/div[@class=&quot;css-12sieg3&quot;]/div[@class=&quot;css-y5gcsw&quot;]/div[@class=&quot;css-5fmc3z&quot;]/div[@class=&quot;css-qa82pd&quot;]/div[@class=&quot;prd_container-card css-1c4umxf&quot;]/div[@class=&quot;pcv3__container css-gfx8z3&quot;]/div[@class=&quot;css-974ipl&quot;]/a[@class=&quot;pcv3__info-content css-gwkf0u&quot;]/div[@class=&quot;prd_link-product-name css-3um8ox&quot;]</value>
      <webElementGuid>80a854b1-3e55-4eaa-a158-b6a57bf7f036</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[5]/div[2]/div[52]/div/div/div/div/div/div[2]/a/div</value>
      <webElementGuid>866ffdfe-7481-49a9-9936-686b5c99335a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ad'])[2]/following::div[2]</value>
      <webElementGuid>2a1a0827-c375-4110-9c19-8c297ecc0eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terjual 1'])[4]/following::div[13]</value>
      <webElementGuid>197452c7-74de-4ab8-9691-f9eaeb4bd2ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp14.980.000'])[1]/preceding::div[1]</value>
      <webElementGuid>bca94bdc-08a5-4803-8d1a-4014bf85c8af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cashback 2%'])[1]/preceding::div[2]</value>
      <webElementGuid>edb82f67-eff6-401a-9015-da8e4914e206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apple iPhone 14 5G 512GB 256GB 128GB 512 256 128 GB Garansi 1 Tahun']/parent::*</value>
      <webElementGuid>5d6cef03-32c3-41bb-88f8-77c5ce5c0ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[52]/div/div/div/div/div/div[2]/a/div</value>
      <webElementGuid>c4735d73-3832-48c7-af59-06a2a62f4c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Apple iPhone 14 5G 512GB 256GB 128GB 512 256 128 GB Garansi 1 Tahun' or . = 'Apple iPhone 14 5G 512GB 256GB 128GB 512 256 128 GB Garansi 1 Tahun')]</value>
      <webElementGuid>9b4dca51-06ee-48a6-a176-2e1d6b8f6ca5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
