<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>item39</name>
   <tag></tag>
   <elementGuidId>e85d1fc0-a504-4693-bfbd-f18f6fb36890</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[5]/div[2]/div[29]/div/div/div/div/div/div[2]/a/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7aaefeb5-a4ae-4f80-8c2c-68ee46607314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prd_link-product-name css-3um8ox</value>
      <webElementGuid>3479a054-c516-4ed6-a70b-369152f62316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>spnSRPProdName</value>
      <webElementGuid>7b8aceac-b145-4b0a-b6c7-ba6b69b6efbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>READY Apple iPhone 14 Pro Max 128GB 256GB 512GB Garansi Resmi iBox</value>
      <webElementGuid>ee35185e-0963-4a10-af40-785fab502e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[@class=&quot;css-jau1bt&quot;]/div[@class=&quot;css-1c82svt&quot;]/div[@class=&quot;css-rjanld&quot;]/div[5]/div[@class=&quot;css-jza1fo&quot;]/div[@class=&quot;css-12sieg3&quot;]/div[@class=&quot;css-y5gcsw&quot;]/div[@class=&quot;css-5fmc3z&quot;]/div[@class=&quot;css-qa82pd&quot;]/div[@class=&quot;prd_container-card css-1c4umxf&quot;]/div[@class=&quot;pcv3__container css-gfx8z3&quot;]/div[@class=&quot;css-974ipl&quot;]/a[@class=&quot;pcv3__info-content css-gwkf0u&quot;]/div[@class=&quot;prd_link-product-name css-3um8ox&quot;]</value>
      <webElementGuid>ad14e0ba-d1f2-4cd9-9668-50a803bc6872</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[5]/div[2]/div[29]/div/div/div/div/div/div[2]/a/div[2]</value>
      <webElementGuid>6c46286d-e65c-4520-9dc9-0d4af607a803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk Terbaru'])[6]/following::div[1]</value>
      <webElementGuid>1e0f892d-d7fc-470a-a265-fa188fab3db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='toko electronia'])[6]/following::div[13]</value>
      <webElementGuid>f32056a5-c37b-4042-b136-98f381f56b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp14.323.500'])[1]/preceding::div[1]</value>
      <webElementGuid>3cf24fcd-351a-4b30-90bb-ea04704ffed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surabaya'])[3]/preceding::div[3]</value>
      <webElementGuid>dd80190c-6075-4ec1-88d5-df5d61c16a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='READY Apple iPhone 14 Pro Max 128GB 256GB 512GB Garansi Resmi iBox']/parent::*</value>
      <webElementGuid>6e63c9ee-b62a-426a-98fb-cd2c7c9cc143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[29]/div/div/div/div/div/div[2]/a/div[2]</value>
      <webElementGuid>dc575e2d-14d0-49d1-9a57-e6b49f484bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'READY Apple iPhone 14 Pro Max 128GB 256GB 512GB Garansi Resmi iBox' or . = 'READY Apple iPhone 14 Pro Max 128GB 256GB 512GB Garansi Resmi iBox')]</value>
      <webElementGuid>0faba699-9664-4230-9d15-01c4300e37dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
