<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>item49</name>
   <tag></tag>
   <elementGuidId>0ba7ec04-104c-4ea8-9ac0-82a7821c4e30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[5]/div[2]/div[39]/div/div/div/div/div/div[2]/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b90f2b9c-d6ac-43fe-9f3f-4d9855aed224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prd_link-product-name css-3um8ox</value>
      <webElementGuid>10f43dac-0933-44b6-a41d-344232d9ebd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>spnSRPProdName</value>
      <webElementGuid>cf652e78-6fd1-42bf-9004-e1b98c9e6e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(IBOX) Apple iPhone 14 Pro 1TB 512GB 256GB 128GB 6.1&quot; inch Resmi TAM</value>
      <webElementGuid>7ccf8e81-f12d-468b-9f9e-f1352d39850a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[@class=&quot;css-jau1bt&quot;]/div[@class=&quot;css-1c82svt&quot;]/div[@class=&quot;css-rjanld&quot;]/div[5]/div[@class=&quot;css-jza1fo&quot;]/div[@class=&quot;css-12sieg3&quot;]/div[@class=&quot;css-y5gcsw&quot;]/div[@class=&quot;css-5fmc3z&quot;]/div[@class=&quot;css-qa82pd&quot;]/div[@class=&quot;prd_container-card css-1c4umxf&quot;]/div[@class=&quot;pcv3__container css-gfx8z3&quot;]/div[@class=&quot;css-974ipl&quot;]/a[@class=&quot;pcv3__info-content css-gwkf0u&quot;]/div[@class=&quot;prd_link-product-name css-3um8ox&quot;]</value>
      <webElementGuid>13793881-8ee3-4d64-acf6-6056d3cc9c54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[5]/div[2]/div[39]/div/div/div/div/div/div[2]/a/div</value>
      <webElementGuid>410dac2a-ad83-402e-b83c-5d3e88782ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='lestykejora'])[1]/following::div[12]</value>
      <webElementGuid>faff50fe-6a86-4693-925b-60377253ce15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kab. Banjarnegara'])[1]/following::div[12]</value>
      <webElementGuid>f1bf7b50-c9e7-4215-8677-cc706bb40b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp14.849.250'])[2]/preceding::div[1]</value>
      <webElementGuid>abd7e23b-705c-4e3c-a2b9-d130ed24439e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kab. Banjarnegara'])[2]/preceding::div[3]</value>
      <webElementGuid>612b8c09-5e2f-486c-b9d9-c5aafdca817a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[39]/div/div/div/div/div/div[2]/a/div</value>
      <webElementGuid>45ad1564-5c94-4989-bee8-071b6da95f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '(IBOX) Apple iPhone 14 Pro 1TB 512GB 256GB 128GB 6.1&quot; inch Resmi TAM' or . = '(IBOX) Apple iPhone 14 Pro 1TB 512GB 256GB 128GB 6.1&quot; inch Resmi TAM')]</value>
      <webElementGuid>71fcdf13-1db4-4f9d-9b4f-7596d2846ae4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
